name: CI_testSomme

on:
    push:
        branches: dev
    pull_request:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Verification du code
              uses: actions/checkout@v2

            - name: Configuration de Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '14'

            - name: Installation des dependances
              run: npm install

            - name: Lancement des tests
              run: npm test
    merge:
        needs: build  
        runs-on: ubuntu-latest
        if: success()
        steps:
          - name: Checkout code from dev
            uses: actions/checkout@v2
            with:
              ref: dev

          - name: Merge dans main
            run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git checkout main
                git merge dev
                git push origin main 
            env: 
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: success()
        steps:
          - name: Deploiement sur Heroku
            run: |
                git remote add heroku https://git.heroku.com/integration_continue.git
                git push heroku main
            env:
                HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

