name: CI_testSomme

on:
    push:
        branches: dev
    pull_request:
        branches: dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Verification du code
              uses: actions/checkout@v2

            - name: Configuration de Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '14'

            - name: Installation des dependances
              run: npm install

            - name: Lancement des tests
              run: npm test
    merge:
        needs: build  
        runs-on: ubuntu-latest
        if: success()
        steps:

          - name: Verification de la branche dev
            uses: actions/checkout@v2
            with:
              fetch-depth: 0

          - name: Configuration de git
            run: |
                git config --global user.name "chloe-leonard"
                git config --global user.email "chloe.leonard@epsi.fr"
                
                
          - name: Verification branche main
            run: git checkout main

          - name: Merge de dev dans main
            run: |
                git merge dev
                git push origin main 
            env: 
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: success()
        steps:
          - name: Deploiement sur Heroku
            run: |
                echo "connexion à Heroku"
           

